
services:
  nodejs:
    build: ./nodejs
    networks:
      - my-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
